/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import DataStructure.HashTable;
import static Application.PhoneDirectory.HT;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sameer
 */
public class EditContact extends javax.swing.JFrame {

    /**
     * Creates new form EditContact
     */
    PhoneDirectory p = new PhoneDirectory();
    HashTable HT;
    public EditContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Update_EC = new javax.swing.JButton();
        SecondaryNum_EC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PrimaryNum_EC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Name_EC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Search_Contact_EC = new javax.swing.JTextField();
        Search_EC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 240));

        Update_EC.setText("Update");
        Update_EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ECActionPerformed(evt);
            }
        });

        SecondaryNum_EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondaryNum_ECActionPerformed(evt);
            }
        });

        jLabel3.setText("Secondary Number:");

        PrimaryNum_EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimaryNum_ECActionPerformed(evt);
            }
        });

        jLabel2.setText("Primary Number:");

        Name_EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_ECActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        Search_Contact_EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Contact_ECActionPerformed(evt);
            }
        });

        Search_EC.setText("Go");
        Search_EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ECActionPerformed(evt);
            }
        });

        jLabel4.setText("Search:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Edit Contact");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update_EC)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search_Contact_EC, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Name_EC, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SecondaryNum_EC)
                            .addComponent(PrimaryNum_EC, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_EC)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Search_Contact_EC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search_EC))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name_EC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrimaryNum_EC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SecondaryNum_EC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Update_EC))
                    .addComponent(jLabel4))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ECActionPerformed
        // TODO add your handling code here:
        HT = p.get_HT();
        HT.Delete(Search_Contact_EC.getText());
        JFrame f;
        Contact Updated;
        if (PrimaryNum_EC.getText().isBlank() && !SecondaryNum_EC.getText().isBlank()){
            PrimaryNum_EC.setText(SecondaryNum_EC.getText());
            if(Name_EC.getText().isBlank()) Updated = new Contact("Contact: " + PrimaryNum_EC.getText(),SecondaryNum_EC.getText(),"" );
            else Updated = new Contact(Name_EC.getText(),SecondaryNum_EC.getText(),"" );
            HT.insert(Updated);
            f = new JFrame();
            JOptionPane.showMessageDialog(f, "Contact Updated Sucessfully.");
        this.hide();
        }
        else if(PrimaryNum_EC.getText().isBlank() && SecondaryNum_EC.getText().isBlank()){
            f = new JFrame();
            JOptionPane.showMessageDialog(f, "As there are no Contact Numbers, \n Contact is Deleted");
            this.hide();
        }
        else{
            if(Name_EC.getText().isBlank()) 
                Updated = new Contact("Contact: " + PrimaryNum_EC.getText(), PrimaryNum_EC.getText(), SecondaryNum_EC.getText());
            else      
                Updated = new Contact(Name_EC.getText(), PrimaryNum_EC.getText(), SecondaryNum_EC.getText());
                HT.insert(Updated);
                f = new JFrame();  
                    JOptionPane.showMessageDialog(f, "Contact Updated Sucessfully.");
                this.hide();
        }
        
        
    }//GEN-LAST:event_Update_ECActionPerformed

    private void SecondaryNum_ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondaryNum_ECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondaryNum_ECActionPerformed

    private void PrimaryNum_ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimaryNum_ECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimaryNum_ECActionPerformed

    private void Search_Contact_ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Contact_ECActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Search_Contact_ECActionPerformed

    private void Search_ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ECActionPerformed
        // TODO add your handling code here:
        HT = p.get_HT();
        String n = Search_Contact_EC.getText();
        JFrame f;
        try {
            Contact c = HT.search(n);
            Name_EC.setText(c.name);
            PrimaryNum_EC.setText(c.Num1);
            SecondaryNum_EC.setText(c.Num2);
        } catch (NullPointerException e) {
            f = new JFrame();  
            JOptionPane.showMessageDialog(f, "Contact Does Not Exist.");
        }
    }//GEN-LAST:event_Search_ECActionPerformed

    private void Name_ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_ECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_ECActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name_EC;
    private javax.swing.JTextField PrimaryNum_EC;
    private javax.swing.JTextField Search_Contact_EC;
    private javax.swing.JButton Search_EC;
    private javax.swing.JTextField SecondaryNum_EC;
    private javax.swing.JButton Update_EC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
